### ISSUE TITLE
Preview image size is not equal to the its parent <li>

### ISSUE THREAD

**Issue by enayet-repo** [jakerella/jquerySimpleFilePreview#3]
Thank you for this simple and potential plugin.
I have one opinion for sharing.
There is a big box of preview image generating and that html element is an <li>. But the preview image is showing much smaller in height and width considering the preview box.
I think its more user friendly if the image can occupy the whole space of its parent box.

Only for this I have needed to override css in my project.

Regards

**Comment by jakerella** [comment]
The styles are only intended as one possible way to do it. There are not intended to be the only possible styles. As you see, you were able to override the styles yourself. In fact, you don't need to include my styles at all! I;m not going to be changing the sample code just for this, but thanks for the feedback!

**Comment by enayet-repo** [comment]
Thanks for your quick reply!
